version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.30
    volumes:
      - '~/db-projects/mysql/api-go:/var/lib/mysql'
    ports:
      - "33060:3306"
    restart: always
    environment:
      MYSQL_DATABASE: "test_database"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
