// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"github.com/yeisonLucio/shopping-cart/src"
	"github.com/yeisonLucio/shopping-cart/src/helpers"
	"github.com/yeisonLucio/shopping-cart/src/providers/app"
	"github.com/yeisonLucio/shopping-cart/src/providers/product"
	"github.com/yeisonLucio/shopping-cart/src/providers/user"
)

// Injectors from wire.go:

func Initialize() *src.App {
	mysqlProduct := product.ProductRepositoryProvider()
	createProduct := product.CreateProductProvider(mysqlProduct)
	getProduct := product.GetProductProvider(mysqlProduct)
	updateProduct := product.UpdateProductProvider(mysqlProduct)
	getAllProducts := product.GetAllProductsProvider(mysqlProduct)
	deleteProduct := product.DeleteProductProvider(mysqlProduct)
	productController := product.ProductControllerProvider(createProduct, getProduct, updateProduct, getAllProducts, deleteProduct)
	productRoutesV1_0 := product.ProductRoutesProvider(productController)
	mysqlUser := user.UserRepositoryProvider()
	userController := user.UserControllerProvider(mysqlUser)
	helpersHelpers := helpers.NewHelpers()
	registerUserUC := user.RegisterUserUCProvider(helpersHelpers, mysqlUser)
	loginUC := user.LoginUCProvider(helpersHelpers, mysqlUser)
	authController := user.AuthControllerProvider(registerUserUC, loginUC)
	userRoutesV1_0 := user.UserRoutesProvider(userController, authController)
	routes := app.RoutesProvider(productRoutesV1_0, userRoutesV1_0)
	srcApp := app.AppProvider(routes)
	return srcApp
}
